# Generated by Django 4.0.4 on 2022-05-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('financial_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
